# Generated by Django 5.1.6 on 2025-02-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
