# Generated by Django 4.2.18 on 2025-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0003_equip_usuari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='usuari',
        ),
        migrations.AddField(
            model_name='equip',
            name='president',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equip',
            name='estadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tipus_esdeveniment',
            field=models.CharField(choices=[('gol', 'Gol'), ('targeta_groga', 'Targeta Groga'), ('targeta_vermella', 'Targeta Vermella'), ('substitucio', 'Substitució')], max_length=50),
        ),
    ]
