# Generated by Django 4.2.18 on 2025-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0004_remove_equip_usuari_equip_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='gols_encaixats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partits_jugats',
            field=models.IntegerField(default=0),
        ),
    ]
