# Generated by Django 4.2.18 on 2025-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0005_jugador_gols_encaixats_jugador_partits_jugats'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugadors/'),
        ),
    ]
